# Generated by Django 5.1.1 on 2024-09-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_customuser_altura_alter_customuser_ap1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ap1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre',
        ),
    ]
